// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb-Up5Ysy1J6wdKkJWwQ0jMAQhKynYfnI',
    appId: '1:713918076266:web:c306dec03fef92a0738113',
    messagingSenderId: '713918076266',
    projectId: 'auth-39925',
    authDomain: 'auth-39925.firebaseapp.com',
    storageBucket: 'auth-39925.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArXS4-272E1GUSvcujlsVE-OEI1OtgBHw',
    appId: '1:713918076266:android:adb41e371679b96a738113',
    messagingSenderId: '713918076266',
    projectId: 'auth-39925',
    storageBucket: 'auth-39925.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1eIvoSV9WNcLDKt-lGRfrZZ0QXQQWyFk',
    appId: '1:713918076266:ios:7e68a0f3e6993cb8738113',
    messagingSenderId: '713918076266',
    projectId: 'auth-39925',
    storageBucket: 'auth-39925.appspot.com',
    iosClientId: '713918076266-6u2crcnt1hvg9io8cv86ummp90jh73ib.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1eIvoSV9WNcLDKt-lGRfrZZ0QXQQWyFk',
    appId: '1:713918076266:ios:7e68a0f3e6993cb8738113',
    messagingSenderId: '713918076266',
    projectId: 'auth-39925',
    storageBucket: 'auth-39925.appspot.com',
    iosClientId: '713918076266-6u2crcnt1hvg9io8cv86ummp90jh73ib.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth01',
  );
}
